import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import InputComponent from '@/components/Input'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Disney</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.disney.png" />
      </Head>
      <main className={styles.backhome} >
        <div className={styles.logofrp}>
          <img src='/frp.logo.png' alt='logo-frp'/>
        </div>
        <div>
        <InputComponent/>
        </div>
       
      </main>
    </div>
  )
}
